import { ServiceItem } from '@/types';

export const INITIAL_SERVICES: ServiceItem[] = [
  // 1. Xerox Services
  {
    id: 'srv-xerox-bw-ss',
    name: 'Xerox B&W (Single Side)',
    name_ta: 'ஜெராக்ஸ் கருப்பு-வெள்ளை (ஒரு பக்கம்)',
    category: 'XEROX',
    default_unit_price: 2,
    unit_label: 'page',
    is_active: true,
  },
  {
    id: 'srv-xerox-bw-ds',
    name: 'Xerox B&W (Double Side / Back-to-Back)',
    name_ta: 'ஜெராக்ஸ் கருப்பு-வெள்ளை (இரு பக்கம்)',
    category: 'XEROX',
    default_unit_price: 3,
    unit_label: 'sheet',
    is_active: true,
  },
  {
    id: 'srv-xerox-col-ss',
    name: 'Color Xerox (Single Side)',
    name_ta: 'வண்ண ஜெராக்ஸ் (ஒரு பக்கம்)',
    category: 'XEROX',
    default_unit_price: 10,
    unit_label: 'page',
    is_active: true,
  },
  {
    id: 'srv-xerox-col-ds',
    name: 'Color Xerox (Double Side)',
    name_ta: 'வண்ண ஜெராக்ஸ் (இரு பக்கம்)',
    category: 'XEROX',
    default_unit_price: 18,
    unit_label: 'sheet',
    is_active: true,
  },

  // 2. Printouts
  {
    id: 'srv-print-bw',
    name: 'B&W Document Printout (A4)',
    name_ta: 'கருப்பு-வெள்ளை பிரிண்ட் (A4)',
    category: 'PRINT',
    default_unit_price: 5,
    unit_label: 'page',
    is_active: true,
  },
  {
    id: 'srv-print-col',
    name: 'Color Document Printout (A4)',
    name_ta: 'வண்ண பிரிண்ட் (A4)',
    category: 'PRINT',
    default_unit_price: 15,
    unit_label: 'page',
    is_active: true,
  },
  {
    id: 'srv-print-photo-pass',
    name: 'Passport Size Photo (8 Copies)',
    name_ta: 'பாஸ்போர்ட் புகைப்படம் (8 பிரதிகள்)',
    category: 'PRINT',
    default_unit_price: 50,
    unit_label: 'set',
    is_active: true,
  },
  {
    id: 'srv-print-photo-gloss',
    name: 'Glossy Photo Print (4x6 / A4)',
    name_ta: 'புகைப்பட பிரிண்ட் (Glossy)',
    category: 'PRINT',
    default_unit_price: 40,
    unit_label: 'photo',
    is_active: true,
  },

  // 3. Lamination & Binding
  {
    id: 'srv-lam-id',
    name: 'ID Card / Aadhaar Lamination',
    name_ta: 'அடையாள அட்டை லேமினேஷன்',
    category: 'LAMINATION',
    default_unit_price: 20,
    unit_label: 'card',
    is_active: true,
  },
  {
    id: 'srv-lam-a4',
    name: 'A4 Certificate Lamination',
    name_ta: 'A4 சான்றிதழ் லேமினேஷன்',
    category: 'LAMINATION',
    default_unit_price: 40,
    unit_label: 'sheet',
    is_active: true,
  },
  {
    id: 'srv-bind-spiral',
    name: 'Spiral Binding (Document / Project)',
    name_ta: 'ஸ்பைரல் பைண்டிங்',
    category: 'LAMINATION',
    default_unit_price: 50,
    unit_label: 'book',
    is_active: true,
  },
  {
    id: 'srv-scan-mail',
    name: 'Scanning & PDF / Email Send',
    name_ta: 'ஸ்கேனிங் & இமெயில்',
    category: 'LAMINATION',
    default_unit_price: 15,
    unit_label: 'doc',
    is_active: true,
  },

  // 4. Online E-Services (இ-சேவை மையம்)
  {
    id: 'srv-esev-cert',
    name: 'Community / Income / Nativity Certificate',
    name_ta: 'சாதி / வருமானம் / இருப்பிட சான்றிதழ்',
    category: 'E_SERVICE',
    default_unit_price: 120,
    unit_label: 'appl',
    is_active: true,
  },
  {
    id: 'srv-esev-patta',
    name: 'Patta / Chitta / FMB Download & Print',
    name_ta: 'பட்டா / சிட்டா நகல்',
    category: 'E_SERVICE',
    default_unit_price: 80,
    unit_label: 'copy',
    is_active: true,
  },
  {
    id: 'srv-esev-pan',
    name: 'New PAN Card / Correction Application',
    name_ta: 'புதிய பான் கார்டு விண்ணப்பம்',
    category: 'E_SERVICE',
    default_unit_price: 150,
    unit_label: 'appl',
    is_active: true,
  },
  {
    id: 'srv-esev-aadhaar',
    name: 'Aadhaar Download / PVC Card Order',
    name_ta: 'ஆதார் பதிவிறக்கம் / PVC அட்டை',
    category: 'E_SERVICE',
    default_unit_price: 50,
    unit_label: 'card',
    is_active: true,
  },
  {
    id: 'srv-esev-eb',
    name: 'TNEB Electricity Bill Payment (Service Charge)',
    name_ta: 'மின் கட்டணம் செலுத்துதல்',
    category: 'E_SERVICE',
    default_unit_price: 20,
    unit_label: 'bill',
    is_active: true,
  },
  {
    id: 'srv-esev-voter',
    name: 'Voter ID Application / Address Change',
    name_ta: 'வாக்காளர் அடையாள அட்டை மாற்றம்',
    category: 'E_SERVICE',
    default_unit_price: 80,
    unit_label: 'appl',
    is_active: true,
  },
  {
    id: 'srv-esev-money',
    name: 'Money Transfer / AEPS Cash Withdrawal (Commission)',
    name_ta: 'பணம் அனுப்புதல் / எடுக்கும் கட்டணம்',
    category: 'E_SERVICE',
    default_unit_price: 30,
    unit_label: 'tx',
    is_active: true,
  },

  // 5. Stationery Items
  {
    id: 'srv-stat-pen',
    name: 'Ball Pen / Gel Pen (Blue / Black)',
    name_ta: 'பேனா (நீலம் / கருப்பு)',
    category: 'STATIONERY',
    default_unit_price: 10,
    unit_label: 'piece',
    is_active: true,
  },
  {
    id: 'srv-stat-file',
    name: 'Office Stick File / Folder',
    name_ta: 'ஸ்டிக் ஃபைல் / கோப்பு',
    category: 'STATIONERY',
    default_unit_price: 15,
    unit_label: 'piece',
    is_active: true,
  },
  {
    id: 'srv-stat-env',
    name: 'Cloth Envelope (A4 / Legal)',
    name_ta: 'துணி உறை (A4 கவர்)',
    category: 'STATIONERY',
    default_unit_price: 10,
    unit_label: 'piece',
    is_active: true,
  },
];
